-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.4.3 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table platinum.tbl_packages
CREATE TABLE IF NOT EXISTS `tbl_packages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `studio_id` bigint unsigned NOT NULL,
  `category_id` bigint unsigned NOT NULL,
  `package_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `package_description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `package_inclusions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `duration` int DEFAULT NULL,
  `maximum_edited_photos` int NOT NULL,
  `coverage_scope` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `package_location` json DEFAULT NULL,
  `allow_multiple_locations` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Determines if package allows multiple shooting locations',
  `max_locations` int DEFAULT '1' COMMENT 'Maximum number of locations allowed (1-10)',
  `allow_time_customization` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 = Fixed duration only, 1 = Clients can customize time',
  `package_price` decimal(10,2) NOT NULL,
  `online_gallery` tinyint(1) NOT NULL DEFAULT '0',
  `photographer_count` int NOT NULL DEFAULT '0',
  `status` enum('active','inactive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tbl_packages_studio_id_index` (`studio_id`),
  KEY `tbl_packages_category_id_index` (`category_id`),
  KEY `tbl_packages_status_index` (`status`),
  CONSTRAINT `tbl_packages_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `tbl_categories` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tbl_packages_studio_id_foreign` FOREIGN KEY (`studio_id`) REFERENCES `tbl_studios` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tbl_packages_chk_1` CHECK (json_valid(`package_inclusions`)),
  CONSTRAINT `tbl_packages_chk_2` CHECK (json_valid(`coverage_scope`))
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table platinum.tbl_packages: ~18 rows (approximately)
INSERT INTO `tbl_packages` (`id`, `studio_id`, `category_id`, `package_name`, `package_description`, `package_inclusions`, `duration`, `maximum_edited_photos`, `coverage_scope`, `package_location`, `allow_multiple_locations`, `max_locations`, `allow_time_customization`, `package_price`, `online_gallery`, `photographer_count`, `status`, `created_at`, `updated_at`) VALUES
	(1, 1, 1, 'Intimate Wedding - Essential', 'Perfect for intimate weddings with up to 50 guests. Captures the heartfelt moments of your special day without overwhelming coverage.', '["6 hours of wedding day coverage","1 professional photographer","300+ edited high-resolution photos","Online gallery with download access","USB keepsake box with selected photos","Pre-wedding consultation"]', 6, 300, '[]', '["In-Studio"]', 0, 1, 0, 35000.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(2, 1, 1, 'Classic Wedding - Premium', 'Comprehensive coverage for traditional weddings with full-day documentation. Includes pre-nuptial shoot and all major wedding events.', '["10 hours of wedding day coverage","1 main photographer + 1 assistant photographer","Pre-nuptial photoshoot (4 hours, 1 location)","500+ edited high-resolution photos","Same-day edit (SDE) video highlights","Online gallery with download & print rights","Premium leather album (20 pages)","USB box with wooden case","2 pre-wedding consultations"]', 10, 500, '["Metro Manila","Cavite","Laguna","Rizal","Bulacan"]', '["On-Location"]', 1, 3, 0, 75000.00, 1, 2, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(3, 1, 1, 'Luxury Wedding - Elite', 'Ultimate luxury coverage for grand weddings. Two photographers capturing every angle, full-day coverage, pre-nuptial destination shoot, and premium album.', '["12+ hours of wedding day coverage (unlimited until after reception)","2 main photographers + 1 videographer","Pre-nuptial destination shoot (full day, up to 3 locations)","800+ edited high-resolution photos","5-7 minute cinematic wedding film","Full ceremony & speeches video (raw + edited)","Online gallery with print rights & mobile app","Premium coffee table album (40 pages)","Canvas print (24x36 inches)","All photos in custom wooden box with USB","Unlimited pre-wedding consultations","Wedding coordinator assistance on photo timeline"]', NULL, 800, '["Nationwide (Luzon, Visayas, Mindanao)","Travel fees included for Luzon"]', '["In-Studio", "On-Location"]', 1, 5, 1, 150000.00, 1, 3, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(4, 1, 2, 'Corporate Event - Basic Coverage', 'Perfect for seminars, conferences, and corporate gatherings. Professional documentation of speakers, attendees, and key moments.', '["4 hours of event coverage","1 professional photographer","200+ edited high-resolution photos","Candid shots of speakers and attendees","Stage\\/lectern coverage","Group photo documentation","Online gallery with download access","3-day turnaround time"]', 4, 200, '["Metro Manila","Cavite","Laguna"]', '["On-Location"]', 0, 1, 0, 18000.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(5, 1, 2, 'Birthday Celebration - Family Package', 'Capture the joy and laughter of your child\'s special day. From preparations to the party, we document every smile, every cake moment, and every fun activity.', '["5 hours of event coverage","1 main photographer","300+ edited high-resolution photos","Preparation shots (before party)","Cake cutting ceremony","Candid guest interactions","Family portraits","Online gallery with download access","USB drive with selected photos","10 printed 4x6 photos in keepsake box"]', 5, 300, '["Metro Manila","Cavite"]', '["On-Location"]', 0, 1, 0, 22000.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(6, 1, 2, 'Corporate Gala & Awards Night - Premium', 'Comprehensive coverage for formal corporate events, anniversary celebrations, and awards nights. Includes red carpet coverage, formal portraits, and full event documentation.', '["8 hours of event coverage","2 professional photographers","Red carpet arrival coverage","600+ edited high-resolution photos","Award ceremony documentation","Executive portraits","Sponsor booth coverage","Event highlights slideshow","Online gallery with print rights","Premium leather album (30 pages)","All photos on custom USB","5-day turnaround with priority editing"]', 8, 600, '["Metro Manila","Cavite","Laguna","Rizal","Bulacan","Pampanga"]', '["On-Location"]', 1, 3, 1, 55000.00, 1, 2, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(7, 1, 3, 'Family Mini Session', 'A quick and fun 30-minute session perfect for families with young children. Ideal for holiday cards, updated family photos, or simple portraits.', '["30-minute studio session","1 photographer","20 edited high-resolution photos","5 digital downloads with print release","Simple backdrop setup","Online gallery access","2-week turnaround"]', 1, 20, '[]', '["In-Studio"]', 0, 1, 0, 4500.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(8, 1, 3, 'Family Legacy Session', 'A comprehensive family portrait experience for extended families. Perfect for reunions, multi-generational gatherings, and milestone celebrations.', '["2-hour studio or outdoor session","1 lead photographer + 1 assistant","60+ edited high-resolution photos","Individual family group shots","Extended family group portraits","Candid lifestyle moments","Online gallery with download & print rights","Canvas print (16x20 inches)","Premium photo album (20 pages)","All photos on custom USB"]', 2, 60, '["Studio or on-location within Metro Manila"]', '["In-Studio", "On-Location"]', 1, 2, 1, 18500.00, 1, 2, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(9, 1, 3, 'Newborn & Maternity Bundle', 'Capture the beautiful journey from pregnancy to welcoming your little one. Includes both maternity and newborn sessions with a cohesive style.', '["Maternity session (1 hour)","Newborn session (2-3 hours)","1 photographer specializing in newborns","80+ edited high-resolution photos (combined)","Props, wraps, and accessories included","Parent and sibling shots","Online gallery with download access","Premium leather album (30 pages)","2 framed prints (8x10 inches)","USB with all images"]', 4, 80, '[]', '["In-Studio"]', 0, 1, 0, 22000.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(10, 1, 4, 'E-Commerce Starter Pack', 'Perfect for online sellers and small businesses. Clean, professional product photos optimized for e-commerce platforms.', '["Up to 20 products","5 shots per product (different angles)","White background standard","Basic color correction","High-resolution JPEG files","Watermark-free images","2-day turnaround","Simple styling assistance"]', 3, 100, '[]', '["In-Studio"]', 0, 1, 0, 8500.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(11, 1, 4, 'Lifestyle Product Suite', 'Showcase your products in real-life settings. Perfect for social media content, lookbooks, and marketing materials.', '["Up to 15 products","Lifestyle shots with models (2 models included)","Studio and outdoor setup options","Creative prop styling","10 detail shots per product","Advanced retouching included","Social media ready (square\\/portrait formats)","Commercial usage rights","Online gallery with download access"]', 5, 150, '["Metro Manila area"]', '["In-Studio", "On-Location"]', 1, 2, 1, 28000.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(12, 1, 4, 'Catalog & Lookbook Production', 'Full-scale product photography for catalogs, lookbooks, and advertising campaigns. Professional styling, models, and post-production included.', '["Full day shoot (8 hours)","Up to 50 products","2 professional photographers","Professional stylist included","2 models included","Studio rental included","Advanced retouching and color grading","200+ final images","Full commercial usage rights","Customized background options","Video content add-on available","5-day priority turnaround"]', 8, 200, '["Nationwide, travel fees apply outside Metro Manila"]', '["In-Studio", "On-Location"]', 1, 3, 1, 65000.00, 1, 2, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(13, 1, 10, 'Pawsome Portrait Session', 'A fun and relaxed session to capture your furry friend\'s unique personality. Perfect for dogs, cats, and small pets.', '["1-hour studio or outdoor session","1 photographer experienced with pets","25 edited high-resolution photos","Patience and treat-motivated approach","Simple backdrop options","Owner can join for couple of shots","Online gallery with download access","Digital photo release"]', 1, 25, '[]', '["In-Studio", "On-Location"]', 1, 2, 0, 5500.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(14, 1, 10, 'Pet & Family Bonding', 'Capture the special bond between your family and your beloved pet. Includes candid moments and posed portraits.', '["2-hour session at your home or park","1 photographer","50+ edited high-resolution photos","Candid and posed shots","Family portraits with pet","Solo pet portraits","Action shots (running, playing)","Online gallery with print rights","Canvas print (11x14 inches)","Custom pet-themed USB drive"]', 2, 50, '["Metro Manila","Cavite"]', '["On-Location"]', 1, 2, 1, 12500.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(15, 1, 10, 'Premium Pet Portfolio', 'The ultimate pet photography experience. Professional styling, multiple locations, and a custom album to cherish forever.', '["3-hour session","2 photographers","2 location options (studio + outdoor)","Pet stylist on-site (grooming touch-ups)","100+ edited high-resolution photos","Professional props and accessories","Action and slow-motion video clips","Custom leather album (20 pages)","Framed print (16x20 inches)","Online gallery with unlimited downloads","Mobile app access for easy sharing","Premium USB in keepsake box"]', 3, 100, '["Metro Manila, Cavite, Laguna"]', '["In-Studio", "On-Location"]', 1, 2, 1, 25000.00, 1, 2, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(16, 1, 6, 'Portfolio Builder', 'Perfect for aspiring models, designers, and fashion students. Build your portfolio with professional, editorial-quality images.', '["2-hour studio session","1 photographer","3 outfit changes","Professional styling advice","Basic makeup touch-up","40 edited high-resolution photos","Online gallery with download access","Portfolio-ready digital files"]', 2, 40, '[]', '["In-Studio"]', 0, 1, 0, 12000.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(17, 1, 6, 'Editorial Fashion Shoot', 'High-end fashion photography suitable for magazines, lookbooks, and advertising campaigns. Professional styling and makeup team included.', '["4-hour session","1 lead fashion photographer","Professional HMUA included","Professional stylist included","Up to 5 outfit changes","Studio rental with premium backdrops","100+ edited high-resolution photos","Advanced retouching and color grading","Online gallery with commercial rights","Behind-the-scenes video highlights","Print-ready files for publication"]', 4, 100, '[]', '["In-Studio", "On-Location"]', 1, 2, 1, 35000.00, 1, 1, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04'),
	(18, 1, 6, 'Campaign Production', 'Full-scale fashion campaign production for brands and designers. Includes creative direction, multiple models, and video content.', '["Full day shoot (8-10 hours)","2 fashion photographers","Creative director included","Professional HMUA team (2 stylists)","Models (up to 3 included)","Custom set design and props","200+ edited high-resolution photos","30-second campaign video","Behind-the-scenes documentary","Full commercial usage rights","Digital press kit","Social media campaign assets","Campaign launch consultation"]', 10, 200, '["Metro Manila, travel fees for outside locations"]', '["In-Studio", "On-Location"]', 1, 3, 1, 120000.00, 1, 2, 'active', '2026-03-26 05:01:04', '2026-03-26 05:01:04');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
