@extends('layouts.owner.app')
@section('title', 'AI Assistant Configuration')

{{-- CONTENT --}}
@section('content')
    <div class="content-page">
        <div class="container-fluid">
            <div class="row mt-3">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">AI Assistant Configuration</h4>
                        </div>
                        <div class="card-body">
                            <div class="alert alert-info">
                                <i class="ti ti-robot me-1"></i>
                                Replies are generated by the AI assistant, which answers photography-service
                                questions only. The settings below control how it introduces itself and what
                                studio facts it may use. Its security rules are fixed and cannot be edited here.
                            </div>

                            <ul class="nav nav-tabs mb-3" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <a href="#general_settings" data-bs-toggle="tab" class="nav-link active" role="tab">
                                        <i class="ti ti-settings me-1"></i>General Settings
                                    </a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a href="#manage_intents" data-bs-toggle="tab" class="nav-link" role="tab">
                                        <i class="ti ti-message-circle me-1"></i>Studio Knowledge
                                    </a>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <a href="#conversation_history" data-bs-toggle="tab" class="nav-link" role="tab">
                                        <i class="ti ti-history me-1"></i>Conversation History
                                    </a>
                                </li>
                            </ul>

                            <div class="tab-content">
                                {{-- GENERAL SETTINGS TAB --}}
                                <div class="tab-pane active show" id="general_settings" role="tabpanel">
                                    <form id="chatbotConfigForm">
                                        <div class="row g-3">
                                            <div class="col-md-6">
                                                <label for="config_name" class="form-label">Configuration Name</label>
                                                <input type="text" class="form-control" id="config_name" name="config_name"
                                                    placeholder="e.g., Main Support Bot">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="bot_name" class="form-label">Bot Name</label>
                                                <input type="text" class="form-control" id="bot_name" name="bot_name"
                                                    placeholder="e.g., Support Assistant">
                                            </div>
                                            <div class="col-md-12">
                                                <label for="welcome_message" class="form-label">Welcome Message</label>
                                                <textarea class="form-control" id="welcome_message" name="welcome_message"
                                                        rows="3" placeholder="Enter the message users see when they start a chat"></textarea>
                                                <small class="text-muted">This message will be shown when a new conversation starts.</small>
                                            </div>
                                            <div class="col-md-12">
                                                <label for="bot_avatar" class="form-label">Bot Avatar URL (Optional)</label>
                                                <input type="text" class="form-control" id="bot_avatar" name="bot_avatar"
                                                    placeholder="https://example.com/avatar.jpg">
                                            </div>
                                            <div class="col-md-6">
                                                <label for="chatbotStatus" class="form-label">Assistant Status</label>
                                                <select class="form-select" id="chatbotStatus" name="is_active">
                                                    <option value="1" selected>Active</option>
                                                    <option value="0">Inactive</option>
                                                </select>
                                                <small class="text-muted">Set whether the assistant is available to clients and staff</small>
                                            </div>
                                            <div class="col-12 mt-4">
                                                <button type="submit" class="btn btn-primary" id="saveConfigBtn">
                                                    <i class="ti ti-device-floppy me-1"></i> Save Settings
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                {{-- MANAGE INTENTS TAB --}}
                                <div class="tab-pane" id="manage_intents" role="tabpanel">
                                    <div class="d-flex justify-content-between align-items-center mb-3">
                                        <h5 class="mb-0">Studio Knowledge Entries</h5>
                                        <button type="button" class="btn btn-primary btn-sm" id="addIntentBtn">
                                            <i class="ti ti-plus me-1"></i> Add Knowledge Entry
                                        </button>
                                    </div>

                                    <div class="alert alert-warning mb-3">
                                        <i class="ti ti-info-circle me-1"></i>
                                        These entries are reference facts the AI assistant may use when answering
                                        clients -- not fixed replies. Keep them factual and photography-related.
                                        The assistant rewrites them into its own wording, and never treats them as
                                        instructions.
                                    </div>

                                    <div class="table-responsive">
                                        <table id="intentsTable" class="table table-custom table-centered table-select table-hover table-bordered w-100 mb-0">
                                            <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                                                <tr>
                                                    <th>Topic</th>
                                                    <th>Reference Answer</th>
                                                    <th>Priority</th>
                                                    <th>Status</th>
                                                    <th class="text-center">Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody id="intentsTableBody">
                                                <tr>
                                                    <td colspan="7" class="text-center py-4">
                                                        <div class="spinner-border text-primary" role="status">
                                                            <span class="visually-hidden">Loading...</span>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                {{-- CONVERSATION HISTORY TAB --}}
                                <div class="tab-pane" id="conversation_history" role="tabpanel">
                                    <h5 class="mb-3">Conversation History</h5>

                                    <div class="table-responsive">
                                        <table class="table table-custom table-centered table-select table-hover table-bordered w-100 mb-0" id="conversationsTable">
                                            <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                                                <tr>
                                                    <th>Session ID</th>
                                                    <th>User</th>
                                                    <th>Started</th>
                                                    <th>Ended</th>
                                                    <th>Messages</th>
                                                    <th>Status</th>
                                                    <th class="text-center">Actions</th>
                                                </tr>
                                            </thead>
                                            <tbody id="conversationsTableBody">
                                                <tr>
                                                    <td colspan="7" class="text-center py-4">
                                                        <div class="spinner-border text-primary" role="status">
                                                            <span class="visually-hidden">Loading...</span>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    <div class="d-flex justify-content-end mt-3" id="conversationsPagination"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- Intent Modal --}}
    <div class="modal fade" id="intentModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="intentModalTitle">Add Knowledge Entry</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="intentForm">
                    <input type="hidden" id="intent_id" name="intent_id">
                    <input type="hidden" id="config_id" name="config_id" value="">

                    <div class="modal-body">
                        <div class="alert alert-info mb-3" id="configInfoBanner" style="display: none;">
                            <i class="ti ti-info-circle me-1"></i>
                            <span id="configInfoText">Adding intent to: <strong>Loading...</strong></span>
                        </div>

                        <div class="row g-3">
                            <div class="col-md-6">
                                <label for="intent_name" class="form-label">Topic <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="intent_name" name="intent_name" required>
                                <small class="text-muted">A short topic name (e.g., "Pricing Inquiry")</small>
                            </div>

                            <div class="col-md-6">
                                <label for="priority" class="form-label">Priority</label>
                                <input type="number" class="form-control" id="priority" name="priority" min="0" max="100" value="0">
                                <small class="text-muted">Higher priority entries are offered to the assistant first</small>
                            </div>

                            <div class="col-12">
                                <label for="response_text" class="form-label">Reference Answer <span class="text-danger">*</span></label>
                                <textarea class="form-control" id="response_text" name="response_text" rows="4" required></textarea>
                                <small class="text-muted">The facts the assistant should use for this topic. It rewrites this in its own words rather than repeating it verbatim.</small>
                            </div>

                            <div class="col-12">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="is_active" name="is_active" checked>
                                    <label class="form-check-label" for="is_active">Active</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" id="saveIntentBtn">Save Intent</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{-- View Intent Modal --}}
    <div class="modal fade" id="viewIntentModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-semibold" id="viewIntentModalTitle">
                        <i class="ti ti-message-circle me-2"></i>Intent Details
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body p-4">
                    <div class="row align-items-center mb-4">
                        <div class="col-12 col-lg-8">
                            <div class="d-flex align-items-center flex-column flex-md-row">
                                <div class="flex-shrink-0 mb-3 mb-md-0">
                                    <div class="bg-light-primary rounded-circle p-3" style="width: 80px; height: 80px;">
                                        <i class="ti ti-message-circle fs-1 text-primary"></i>
                                    </div>
                                </div>
                            
                                <div class="flex-grow-1 ms-md-4 text-center text-md-start">
                                    <h2 class="mb-1 h3 h3-md" id="viewIntentName">Loading...</h2>
                                    <div class="d-flex align-items-center justify-content-center justify-content-md-start mb-2 flex-wrap">
                                        <span class="badge badge-soft-success p-1" id="viewIntentStatus">Active</span>
                                        <span class="badge badge-soft-info ms-2" id="viewIntentPriority">Priority: 0</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row mb-3">
                        <div class="col">

                            {{-- Response Text --}}
                            <div class="row g-2 mb-4">
                                <h5 class="card-title text-primary">
                                    <i class="ti ti-message-reply me-2"></i>Response Text
                                </h5>
                                <div class="col-12">
                                    <div class="bg-light p-3 rounded" id="viewIntentResponseText">
                                        Loading...
                                    </div>
                                </div>
                            </div>

                            {{-- Metadata --}}
                            <div class="row g-2">
                                <h5 class="card-title text-primary">
                                    <i class="ti ti-info-circle me-2"></i>Metadata
                                </h5>
                                <div class="col-12 col-md-6">
                                    <div class="d-flex align-items-start">
                                        <div class="flex-shrink-0">
                                            <div class="bg-light-primary rounded-circle p-2">
                                                <i class="ti ti-calendar fs-20 text-primary"></i>
                                            </div>
                                        </div>
                                        <div class="flex-grow-1 ms-3">
                                            <label class="text-muted small mb-1">Created At</label>
                                            <p class="mb-0 fw-medium" id="viewIntentCreatedAt">Loading...</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="d-flex align-items-start">
                                        <div class="flex-shrink-0">
                                            <div class="bg-light-primary rounded-circle p-2">
                                                <i class="ti ti-clock fs-20 text-primary"></i>
                                            </div>
                                        </div>
                                        <div class="flex-grow-1 ms-3">
                                            <label class="text-muted small mb-1">Last Updated</label>
                                            <p class="mb-0 fw-medium" id="viewIntentUpdatedAt">Loading...</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="d-flex align-items-start">
                                        <div class="flex-shrink-0">
                                            <div class="bg-light-primary rounded-circle p-2">
                                                <i class="ti ti-hash fs-20 text-primary"></i>
                                            </div>
                                        </div>
                                        <div class="flex-grow-1 ms-3">
                                            <label class="text-muted small mb-1">Intent ID</label>
                                            <p class="mb-0 fw-medium" id="viewIntentId">Loading...</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="editFromViewBtn">
                        <i class="ti ti-edit me-1"></i> Edit Intent
                    </button>
                </div>
            </div>
        </div>
    </div>

    {{-- View Conversation Modal --}}
    <div class="modal fade" id="viewConversationModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Conversation Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="chat-history" id="conversationMessages" style="max-height: 400px; overflow-y: auto;">
                        <!-- Messages will be loaded here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

{{-- SCRIPTS --}}
@section('scripts')
    <script>
        $(document).ready(function() {
            // ==================== INITIALIZATION ====================
            
            // Load chatbot config
            loadChatbotConfig();
            
            // Load intents when tab is shown
            $('a[href="#manage_intents"]').on('shown.bs.tab', function() {
                loadIntents();
            });
            
            // Load conversations when tab is shown
            $('a[href="#conversation_history"]').on('shown.bs.tab', function() {
                loadConversations();
            });

            // ==================== GENERAL SETTINGS ====================
            
            // Load chatbot config
            function loadChatbotConfig() {
                $.ajax({
                    url: '{{ route("owner.chatbot.config.get") }}',
                    type: 'GET',
                    success: function(response) {
                        if (response.success) {
                            if (response.config) {
                                $('#config_name').val(response.config.config_name || '');
                                $('#bot_name').val(response.config.bot_name || '');
                                $('#welcome_message').val(response.config.welcome_message || '');
                                $('#bot_avatar').val(response.config.bot_avatar || '');
                                
                                // Update status dropdown
                                $('#chatbotStatus').val(response.config.is_active ? '1' : '0');
                            } else {
                                // Set defaults
                                $('#bot_name').val('Support Assistant');
                                $('#welcome_message').val('Hello! How can I assist you today?');
                                $('#chatbotStatus').val('1'); // Default to Active
                            }
                        } else {
                            Swal.fire('Error', response.message || 'Failed to load configuration', 'error');
                        }
                    },
                    error: function() {
                        Swal.fire('Error', 'Failed to load chatbot configuration', 'error');
                    }
                });
            }

            // Save config form
            $('#chatbotConfigForm').on('submit', function(e) {
                e.preventDefault();
                
                const formData = {
                    config_name: $('#config_name').val(),
                    bot_name: $('#bot_name').val(),
                    welcome_message: $('#welcome_message').val(),
                    bot_avatar: $('#bot_avatar').val(),
                    is_active: $('#chatbotStatus').val() === '1'
                };
                
                $('#saveConfigBtn').prop('disabled', true).html('<i class="ti ti-loader spinner me-1"></i> Saving...');
                
                $.ajax({
                    url: '{{ route("owner.chatbot.config.save") }}',
                    type: 'POST',
                    data: formData,
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    success: function(response) {
                        if (response.success) {
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                text: response.message,
                                timer: 2000,
                                showConfirmButton: false
                            });
                        } else {
                            Swal.fire('Error', response.message || 'Failed to save configuration', 'error');
                        }
                    },
                    error: function(xhr) {
                        const message = xhr.responseJSON?.message || 'Failed to save configuration';
                        Swal.fire('Error', message, 'error');
                    },
                    complete: function() {
                        $('#saveConfigBtn').prop('disabled', false).html('<i class="ti ti-device-floppy me-1"></i> Save Settings');
                    }
                });
            });

            // Toggle chatbot status
            $('#chatbotStatusSwitch').on('change', function() {
                const isActive = $(this).is(':checked');
                
                $.ajax({
                    url: '{{ route("owner.chatbot.config.toggle") }}',
                    type: 'POST',
                    data: {
                        _token: '{{ csrf_token() }}'
                    },
                    success: function(response) {
                        if (response.success) {
                            $('#statusLabel').text(response.is_active ? 'Active' : 'Inactive');
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                text: response.message,
                                timer: 2000,
                                showConfirmButton: false
                            });
                        } else {
                            // Revert switch on error
                            $(this).prop('checked', !isActive);
                            Swal.fire('Error', response.message || 'Failed to update status', 'error');
                        }
                    },
                    error: function() {
                        // Revert switch on error
                        $(this).prop('checked', !isActive);
                        Swal.fire('Error', 'Failed to update chatbot status', 'error');
                    }
                });
            });

            // ==================== INTENT MANAGEMENT ====================
            
            // Load intents
            function loadIntents() {
                $('#intentsTableBody').html(`
                    <tr>
                        <td colspan="7" class="text-center py-4">
                            <div class="spinner-border text-primary" role="status">
                                <span class="visually-hidden">Loading...</span>
                            </div>
                        </td>
                    </tr>
                `);
                
                $.ajax({
                    url: '{{ route("owner.chatbot.intents.get") }}',
                    type: 'GET',
                    success: function(response) {
                        if (response.success) {
                            if (!response.config) {
                                // No config found
                                $('#intentsTableBody').html(`
                                    <tr>
                                        <td colspan="7" class="text-center py-4">
                                            <i class="ti ti-settings-off fs-1 text-warning d-block mb-2"></i>
                                            <h5>No Chatbot Configuration Found</h5>
                                            <p class="text-muted">Please go to <strong>Chatbot Settings</strong> tab and save your configuration first.</p>
                                            <a href="{{ route('owner.chatbot.config') }}" class="btn btn-primary mt-2">
                                                <i class="ti ti-settings me-1"></i> Go to Settings
                                            </a>
                                        </td>
                                    </tr>
                                `);
                            } else {
                                renderIntentsTable(response.intents);
                            }
                        } else {
                            $('#intentsTableBody').html(`
                                <tr>
                                    <td colspan="7" class="text-center text-danger py-4">
                                        ${response.message || 'Failed to load intents'}
                                    </td>
                                </tr>
                            `);
                        }
                    },
                    error: function() {
                        $('#intentsTableBody').html(`
                            <tr>
                                <td colspan="7" class="text-center text-danger py-4">
                                    Failed to load intents. Please try again.
                                </td>
                            </tr>
                        `);
                    }
                });
            }

            // Render intents table
            function renderIntentsTable(intents) {
                if (!intents || intents.length === 0) {
                    $('#intentsTableBody').html(`
                        <tr>
                            <td colspan="7" class="text-center py-4">
                                <i class="ti ti-message-circle-off fs-1 text-muted d-block mb-2"></i>
                                No knowledge entries yet. Click "Add Knowledge Entry" to create your first one.
                            </td>
                        </tr>
                    `);
                    return;
                }
                
                let html = '';
                
                intents.forEach(intent => {
                    const statusBadge = intent.is_active
                        ? '<span class="badge badge-soft-success">Active</span>' 
                        : '<span class="badge badge-soft-secondary">Inactive</span>';
                    
                    const responsePreview = intent.response_text.length > 50 
                        ? intent.response_text.substring(0, 50) + '...' 
                        : intent.response_text;
                    
                    html += `
                        <tr data-id="${intent.id}">
                            <td><strong>${escapeHtml(intent.intent_name)}</strong></td>
                            <td><span class="small">${escapeHtml(responsePreview)}</span></td>
                            <td><span class="badge badge-soft-info">${intent.priority || 0}</span></td>
                            <td>${statusBadge}</td>
                            <td>
                                <button type="button" class="btn view-intent" data-id="${intent.id}" title="View Details">
                                    <i class="ti ti-eye"></i>
                                </button>
                                <button type="button" class="btn edit-intent" data-id="${intent.id}" title="Edit">
                                    <i class="ti ti-edit"></i>
                                </button>
                                <button type="button" class="btn delete-intent" data-id="${intent.id}" title="Delete">
                                    <i class="ti ti-trash"></i>
                                </button>
                            </td>
                        </tr>
                    `;
                });
                
                $('#intentsTableBody').html(html);
            }

            // Helper to escape HTML
            function escapeHtml(text) {
                if (!text) return '';
                const div = document.createElement('div');
                div.textContent = text;
                return div.innerHTML;
            }

            // Add intent button
            $('#addIntentBtn').on('click', function() {
                // First check if config exists
                $.ajax({
                    url: '{{ route("owner.chatbot.config.get") }}',
                    type: 'GET',
                    success: function(response) {
                        if (response.success) {
                            if (response.config) {
                                // Set config_id in hidden field
                                $('#config_id').val(response.config.id);
                                
                                // Show config info banner
                                $('#configInfoText').html(`Adding intent to: <strong>${response.config.name || 'Your Chatbot'}</strong>`);
                                $('#configInfoBanner').show();
                                
                                // Reset and show modal
                                resetIntentForm();
                                $('#intentModalTitle').text('Add Knowledge Entry');
                                $('#intentModal').modal('show');
                            } else {
                                // No config found - show error and redirect to settings
                                Swal.fire({
                                    icon: 'warning',
                                    title: 'No Chatbot Configuration',
                                    text: 'Please create a chatbot configuration first before adding intents.',
                                    showCancelButton: true,
                                    confirmButtonText: 'Go to Settings',
                                    cancelButtonText: 'Cancel'
                                }).then((result) => {
                                    if (result.isConfirmed) {
                                        window.location.href = '{{ route("owner.chatbot.config") }}';
                                    }
                                });
                            }
                        }
                    },
                    error: function() {
                        Swal.fire('Error', 'Failed to load chatbot configuration', 'error');
                    }
                });
            });

            // Edit intent
            $(document).on('click', '.edit-intent', function() {
                const intentId = $(this).data('id');
                
                $.ajax({
                    url: `/owner/chatbot/intents/${intentId}`, // This now uses the getIntent method
                    type: 'GET',
                    success: function(response) {
                        if (response.success) {
                            // Get current config ID
                            $.ajax({
                                url: '{{ route("owner.chatbot.config.get") }}',
                                type: 'GET',
                                success: function(configResponse) {
                                    if (configResponse.success && configResponse.config) {
                                        $('#config_id').val(configResponse.config.id);
                                        
                                        $('#configInfoText').html(`Editing intent in: <strong>${configResponse.config.name || 'Your Chatbot'}</strong>`);
                                        $('#configInfoBanner').show();
                                        
                                        populateIntentForm(response.intent);
                                        $('#intentModalTitle').text('Edit Intent');
                                        $('#intentModal').modal('show');
                                    }
                                }
                            });
                        } else {
                            Swal.fire('Error', response.message || 'Failed to load intent details', 'error');
                        }
                    },
                    error: function() {
                        Swal.fire('Error', 'Failed to load intent details', 'error');
                    }
                });
            });

            // Populate intent form
            function populateIntentForm(intent) {
                $('#intent_id').val(intent.id);
                $('#intent_name').val(intent.intent_name);
                $('#priority').val(intent.priority || 0);
                $('#response_text').val(intent.response_text);
                $('#is_active').prop('checked', intent.is_active);
            }

            // Reset intent form
            function resetIntentForm() {
                $('#intent_id').val('');
                $('#intentForm')[0].reset();
                $('#is_active').prop('checked', true);
            }

            // Submit intent form
            $('#intentForm').on('submit', function(e) {
                e.preventDefault();
                
                const intentId = $('#intent_id').val();
                const configId = $('#config_id').val();
                
                if (!configId) {
                    Swal.fire('Error', 'No chatbot configuration selected. Please save your settings first.', 'error');
                    return;
                }
                
                const url = intentId 
                    ? `/owner/chatbot/intents/${intentId}`
                    : '{{ route("owner.chatbot.intents.store") }}';
                const method = intentId ? 'PUT' : 'POST';
                
                // Collect form data
                const formData = {
                    config_id: configId,  // Include the config_id
                    intent_name: $('#intent_name').val(),
                    priority: $('#priority').val(),
                    response_text: $('#response_text').val(),
                    is_active: $('#is_active').is(':checked')
                };

                $('#saveIntentBtn').prop('disabled', true).html('<i class="ti ti-loader spinner me-1"></i> Saving...');
                
                $.ajax({
                    url: url,
                    type: method,
                    data: JSON.stringify(formData),
                    contentType: 'application/json',
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    success: function(response) {
                        if (response.success) {
                            $('#intentModal').modal('hide');
                            loadIntents();
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                text: response.message,
                                timer: 2000,
                                showConfirmButton: false
                            });
                        } else {
                            Swal.fire('Error', response.message || 'Failed to save intent', 'error');
                        }
                    },
                    error: function(xhr) {
                        const message = xhr.responseJSON?.message || 'Failed to save intent';
                        const errors = xhr.responseJSON?.errors;
                        
                        if (errors) {
                            let errorMsg = message + '\n';
                            Object.keys(errors).forEach(key => {
                                errorMsg += `\n${errors[key].join(', ')}`;
                            });
                            Swal.fire('Validation Error', errorMsg, 'error');
                        } else {
                            Swal.fire('Error', message, 'error');
                        }
                    },
                    complete: function() {
                        $('#saveIntentBtn').prop('disabled', false).html('Save Intent');
                    }
                });
            });

            // Toggle intent status
            $(document).on('click', '.toggle-intent', function() {
                const intentId = $(this).data('id');
                const isActive = $(this).data('active');
                const action = isActive ? 'deactivate' : 'activate';
                
                Swal.fire({
                    icon: 'warning',
                    title: `Confirm ${action}`,
                    text: `Are you sure you want to ${action} this intent?`,
                    showCancelButton: true,
                    confirmButtonColor: isActive ? '#DC3545' : '#28A745',
                    confirmButtonText: `Yes, ${action} it!`
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: `/owner/chatbot/intents/${intentId}/toggle`,
                            type: 'POST',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            success: function(response) {
                                if (response.success) {
                                    loadIntents();
                                    Swal.fire({
                                        icon: 'success',
                                        title: 'Success',
                                        text: response.message,
                                        timer: 2000,
                                        showConfirmButton: false
                                    });
                                } else {
                                    Swal.fire('Error', response.message || 'Failed to update status', 'error');
                                }
                            },
                            error: function() {
                                Swal.fire('Error', 'Failed to update intent status', 'error');
                            }
                        });
                    }
                });
            });

            // Delete intent
            $(document).on('click', '.delete-intent', function() {
                const intentId = $(this).data('id');
                
                Swal.fire({
                    icon: 'warning',
                    title: 'Confirm Delete',
                    text: 'Are you sure you want to delete this intent? This action cannot be undone.',
                    showCancelButton: true,
                    confirmButtonColor: '#DC3545',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: `/owner/chatbot/intents/${intentId}`,
                            type: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            success: function(response) {
                                if (response.success) {
                                    loadIntents();
                                    Swal.fire({
                                        icon: 'success',
                                        title: 'Success',
                                        text: response.message,
                                        timer: 2000,
                                        showConfirmButton: false
                                    });
                                } else {
                                    Swal.fire('Error', response.message || 'Failed to delete intent', 'error');
                                }
                            },
                            error: function() {
                                Swal.fire('Error', 'Failed to delete intent', 'error');
                            }
                        });
                    }
                });
            });

            // View intent details
            $(document).on('click', '.view-intent', function() {
                const intentId = $(this).data('id');
                
                $.ajax({
                    url: `/owner/chatbot/intents/${intentId}`,
                    type: 'GET',
                    success: function(response) {
                        if (response.success) {
                            populateViewIntentModal(response.intent);
                            $('#viewIntentModal').modal('show');
                        } else {
                            Swal.fire('Error', response.message || 'Failed to load intent details', 'error');
                        }
                    },
                    error: function() {
                        Swal.fire('Error', 'Failed to load intent details', 'error');
                    }
                });
            });

            function populateViewIntentModal(intent) {
                // Basic info
                $('#viewIntentName').text(intent.intent_name);
                $('#viewIntentStatus').text(intent.is_active ? 'Active' : 'Inactive')
                    .removeClass('badge-soft-success badge-soft-secondary')
                    .addClass(intent.is_active ? 'badge-soft-success' : 'badge-soft-secondary');
                $('#viewIntentPriority').text(`Priority: ${intent.priority || 0}`);
                $('#viewIntentId').text(`#${intent.id}`);

                // Response text
                $('#viewIntentResponseText').html(intent.response_text ? escapeHtml(intent.response_text).replace(/\n/g, '<br>') : 'No response text');
                // Dates
                if (intent.created_at) {
                    $('#viewIntentCreatedAt').text(new Date(intent.created_at).toLocaleString());
                }
                if (intent.updated_at) {
                    $('#viewIntentUpdatedAt').text(new Date(intent.updated_at).toLocaleString());
                }

                // Store intent ID for edit button
                $('#editFromViewBtn').data('intent-id', intent.id);
            }

            // Edit from view button
            $('#editFromViewBtn').on('click', function() {
                const intentId = $(this).data('intent-id');
                $('#viewIntentModal').modal('hide');
                
                // Trigger edit for this intent
                setTimeout(() => {
                    $(`.edit-intent[data-id="${intentId}"]`).click();
                }, 500);
            });

            // ==================== CONVERSATION HISTORY ====================
            
            let currentPage = 1;
            
            function loadConversations(page = 1) {
                $('#conversationsTableBody').html(`
                    <tr>
                        <td colspan="7" class="text-center py-4">
                            <div class="spinner-border text-primary" role="status">
                                <span class="visually-hidden">Loading...</span>
                            </div>
                        </td>
                    </tr>
                `);
                
                $.ajax({
                    url: '{{ route("owner.chatbot.conversations") }}',
                    type: 'GET',
                    data: { page: page },
                    success: function(response) {
                        if (response.success) {
                            renderConversationsTable(response.conversations.data);
                            renderPagination(response.conversations);
                        } else {
                            $('#conversationsTableBody').html(`
                                <tr>
                                    <td colspan="7" class="text-center text-danger py-4">
                                        ${response.message || 'Failed to load conversations'}
                                    </td>
                                </tr>
                            `);
                        }
                    },
                    error: function() {
                        $('#conversationsTableBody').html(`
                            <tr>
                                <td colspan="7" class="text-center text-danger py-4">
                                    Failed to load conversations. Please try again.
                                </td>
                            </tr>
                        `);
                    }
                });
            }

            function renderConversationsTable(conversations) {
                if (!conversations || conversations.length === 0) {
                    $('#conversationsTableBody').html(`
                        <tr>
                            <td colspan="7" class="text-center py-4">
                                <i class="ti ti-message-off fs-1 text-muted d-block mb-2"></i>
                                No conversations yet.
                            </td>
                        </tr>
                    `);
                    return;
                }
                
                let html = '';
                
                conversations.forEach(conv => {
                    const user = conv.user 
                        ? `${conv.user.first_name} ${conv.user.last_name}` 
                        : 'Guest';
                    
                    const statusBadge = conv.status === 'active' 
                        ? '<span class="badge badge-soft-success">Active</span>' 
                        : '<span class="badge badge-soft-danger">Ended</span>';
                    
                    const started = conv.started_at ? new Date(conv.started_at).toLocaleString() : 'N/A';
                    const ended = conv.ended_at ? new Date(conv.ended_at).toLocaleString() : '—';
                    
                    html += `
                        <tr>
                            <td><span class="small">${conv.session_id}</span></td>
                            <td>${escapeHtml(user)}</td>
                            <td>${started}</td>
                            <td>${ended}</td>
                            <td class="text-center">${conv.message_count || 0}</td>
                            <td>${statusBadge}</td>
                            <td class="text-center">
                                <button type="button" class="btn view-conversation" data-id="${conv.id}" title="View Details">
                                    <i class="ti ti-eye"></i>
                                </button>
                            </td>
                        </tr>
                    `;
                });
                
                $('#conversationsTableBody').html(html);
            }

            function renderPagination(pagination) {
                if (!pagination || pagination.last_page <= 1) {
                    $('#conversationsPagination').empty();
                    return;
                }
                
                let html = '<nav><ul class="pagination">';
                
                // Previous button
                html += `<li class="page-item ${pagination.current_page === 1 ? 'disabled' : ''}">
                    <a class="page-link" href="#" data-page="${pagination.current_page - 1}">Previous</a>
                </li>`;
                
                // Page numbers
                for (let i = 1; i <= pagination.last_page; i++) {
                    if (i === 1 || i === pagination.last_page || (i >= pagination.current_page - 2 && i <= pagination.current_page + 2)) {
                        html += `<li class="page-item ${i === pagination.current_page ? 'active' : ''}">
                            <a class="page-link" href="#" data-page="${i}">${i}</a>
                        </li>`;
                    } else if (i === pagination.current_page - 3 || i === pagination.current_page + 3) {
                        html += '<li class="page-item disabled"><span class="page-link">...</span></li>';
                    }
                }
                
                // Next button
                html += `<li class="page-item ${pagination.current_page === pagination.last_page ? 'disabled' : ''}">
                    <a class="page-link" href="#" data-page="${pagination.current_page + 1}">Next</a>
                </li>`;
                
                html += '</ul></nav>';
                $('#conversationsPagination').html(html);
            }

            // Pagination click
            $(document).on('click', '.pagination a', function(e) {
                e.preventDefault();
                const page = $(this).data('page');
                if (page) {
                    currentPage = page;
                    loadConversations(page);
                }
            });

            // View conversation details
            $(document).on('click', '.view-conversation', function() {
                const conversationId = $(this).data('id');
                
                $.ajax({
                    url: `/owner/chatbot/conversations/${conversationId}`,
                    type: 'GET',
                    success: function(response) {
                        if (response.success) {
                            renderConversationMessages(response.conversation);
                            $('#viewConversationModal').modal('show');
                        } else {
                            Swal.fire('Error', response.message || 'Failed to load conversation details', 'error');
                        }
                    },
                    error: function() {
                        Swal.fire('Error', 'Failed to load conversation details', 'error');
                    }
                });
            });

            function renderConversationMessages(conversation) {
                const user = conversation.user 
                    ? `${conversation.user.first_name} ${conversation.user.last_name}` 
                    : 'Guest';
                
                let html = `
                    <div class="mb-3 p-2 bg-light rounded">
                        <strong>User:</strong> ${escapeHtml(user)}<br>
                        <strong>Session:</strong> ${conversation.session_id}<br>
                        <strong>Started:</strong> ${new Date(conversation.started_at).toLocaleString()}
                    </div>
                    <hr>
                `;
                
                if (conversation.messages && conversation.messages.length > 0) {
                    conversation.messages.forEach(msg => {
                        const isUser = msg.sender_type === 'user';
                        const alignment = isUser ? 'text-end' : 'text-start';
                        const bgClass = isUser ? 'bg-primary text-white' : 'bg-light';
                        const icon = isUser ? 'ti ti-user' : 'ti ti-robot';
                        
                        html += `
                            <div class="mb-3 ${alignment}">
                                <div class="d-inline-block p-2 rounded ${bgClass}" style="max-width: 80%;">
                                    <small><i class="${icon} me-1"></i>${isUser ? 'You' : 'Bot'}</small>
                                    <p class="mb-0">${escapeHtml(msg.message)}</p>
                                    <small class="${isUser ? 'text-white-50' : 'text-muted'}">${new Date(msg.created_at).toLocaleTimeString()}</small>
                                </div>
                            </div>
                        `;
                    });
                } else {
                    html += '<p class="text-muted text-center">No messages in this conversation.</p>';
                }
                
                $('#conversationMessages').html(html);
            }
        });
    </script>
@endsection
